module.exports = {
  Assignment: require('./Assignment'),
  AssignmentSubmission: require('./AssignmentSubmission'),
  Category: require('./Category'),
  Certificate: require('./Certificate'),
  Course: require('./Course'),
  CourseProgress: require('./CourseProgress'),
  Enrollment: require('./Enrollment'),
  InstructorEarnings: require('./InstructorEarnings'),
  Notification: require('./Notification'),
  OTP: require('./OTP'),
  Payment: require('./Payment'),
  Quiz: require('./Quiz'),
  QuizAttempt: require('./QuizAttempt'),
  Review: require('./Review'),
  Section: require('./Section'),
  SubSection: require('./subSection'),
  User: require('./User'),
  // WatchHistory: require('./WatchHistory'),
  Coupon: require('./Coupon'),
};
